import Head from 'next/head'
import MainSlider from './Components/MainSlider'
import Signture from './Components/Signture'
import TopSection from './Components/TopSection'
import ImagesDragDrop from './Components/ImagesDragDrop'
import { Inter } from 'next/font/google'
import { DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Task-1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
      
        <TopSection />

        <DndProvider backend={HTML5Backend}>
          <ImagesDragDrop />
        </DndProvider>

        <MainSlider />
        <Signture />
      </main>
    </>
  )
}
