import Head from 'next/head'
// import MainSlider from './Components/MainSlider'
// import Signture from './Components/Signture'
import TopSection from './Components/TopSection'
import SecondSection from './Components/SecondSection'
import ThirdSection from './Components/ThirdSection'
import FourthSection from './Components/FourthSection'
// import DragAndDropSec from './Components/DragAndDropSec'
import { Inter } from 'next/font/google'


// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Task-1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
      
        <TopSection />
        <SecondSection/>
        <ThirdSection/>
        <FourthSection/>

        {/* <DragAndDropSec/> */}
        {/* <MainSlider />
        <Signture /> */}
      </main>
    </>
  )
}
